# Generated by Django 4.1.7 on 2023-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
